"""Self-contained HTML report.

The document is a single file with inline CSS and no external resources: no
CDN, no web fonts, no scripts, no network requests. This keeps the tool's
promise of 100% local operation - the report can be opened straight from disk
or attached to a CI job without leaking anything or phoning home. Reference
URLs are plain ``<a href>`` links, which are only fetched if the reader clicks
them.

Every dynamic value (service names, image references, finding prose that may
echo untrusted configuration) is HTML-escaped.
"""

from __future__ import annotations

from html import escape

from portcullis.model import Exposure, Finding, ScanResult, Severity

#: Grade badge colours, aligned with the terminal report.
GRADE_COLORS = {
    "A": "#2e7d32",
    "B": "#558b2f",
    "C": "#f9a825",
    "D": "#ef6c00",
    "E": "#e53935",
    "F": "#b71c1c",
}

SEVERITY_COLORS = {
    Severity.CRITICAL: "#b71c1c",
    Severity.HIGH: "#e53935",
    Severity.MEDIUM: "#ef6c00",
    Severity.LOW: "#f9a825",
    Severity.INFO: "#0288d1",
}

EXPOSURE_COLORS = {
    Exposure.INTERNET: "#d32f2f",
    Exposure.LAN: "#ef6c00",
    Exposure.HOST: "#f9a825",
    Exposure.INTERNAL: "#2e7d32",
    Exposure.UNKNOWN: "#9e9e9e",
}

_STYLE = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica,
    Arial, sans-serif;
  line-height: 1.5; margin: 0; padding: 2rem 1rem; color: #1a1a1a; background: #f5f6f8;
}
main { max-width: 60rem; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.2rem; margin: 2rem 0 .75rem; border-bottom: 1px solid #dcdfe4;
  padding-bottom: .3rem; }
.sub { color: #555; margin: 0 0 1.5rem; }
.grade { display: inline-block; min-width: 2.4rem; text-align: center; color: #fff;
  font-weight: 700; font-size: 1.1rem; padding: .15rem .6rem; border-radius: .4rem; }
.summary-line { margin: .75rem 0 0; font-size: 1.05rem; }
table { width: 100%; border-collapse: collapse; background: #fff; border-radius: .5rem;
  overflow: hidden; box-shadow: 0 1px 2px rgba(0,0,0,.06); }
th, td { text-align: left; padding: .5rem .7rem; border-bottom: 1px solid #eceef1;
  font-size: .92rem; }
th { background: #eef1f5; font-weight: 600; }
tr:last-child td { border-bottom: none; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: .88em; background: #eceef1; padding: .05rem .3rem; border-radius: .25rem; }
.badge { display: inline-block; color: #fff; font-size: .72rem; font-weight: 700;
  letter-spacing: .02em; padding: .1rem .45rem; border-radius: .3rem;
  text-transform: uppercase; }
.pill { display: inline-block; font-size: .78rem; font-weight: 600; padding: .05rem .45rem;
  border-radius: 1rem; color: #fff; }
details { background: #fff; border: 1px solid #e2e5ea; border-left-width: 4px;
  border-radius: .4rem; margin: .6rem 0; box-shadow: 0 1px 2px rgba(0,0,0,.04); }
details[open] { box-shadow: 0 2px 8px rgba(0,0,0,.08); }
summary { cursor: pointer; padding: .7rem .9rem; font-weight: 600; display: flex;
  gap: .6rem; align-items: center; list-style: none; }
summary::-webkit-details-marker { display: none; }
summary .title { flex: 1; }
.body { padding: 0 .9rem .9rem; }
.body p { margin: .5rem 0; }
.meta { color: #666; font-size: .82rem; margin: .2rem 0 .6rem; }
.label { font-weight: 700; }
.fix .label { color: #2e7d32; }
.refs { font-size: .82rem; color: #555; word-break: break-all; }
.refs a { color: #1565c0; }
.none { color: #2e7d32; font-weight: 600; }
footer { margin-top: 2.5rem; color: #888; font-size: .8rem; text-align: center; }
@media (prefers-color-scheme: dark) {
  body { background: #16181d; color: #e6e8ec; }
  h2 { border-color: #2c3038; }
  .sub, .meta, .refs, footer { color: #9aa0a8; }
  table { background: #1e2127; box-shadow: none; }
  th { background: #262a31; }
  th, td { border-color: #2c3038; }
  code { background: #2c3038; }
  details { background: #1e2127; border-color: #2c3038; }
  .refs a { color: #7ab4f5; }
}
"""


def render_html(result: ScanResult, *, min_severity: Severity = Severity.INFO) -> str:
    findings = [f for f in result.findings if f.severity >= min_severity]
    parts: list[str] = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en">')
    parts.append("<head>")
    parts.append('<meta charset="utf-8">')
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append("<title>Portcullis security report</title>")
    parts.append(f"<style>{_STYLE}</style>")
    parts.append("</head>")
    parts.append("<body><main>")
    parts.append(_render_header(result))
    parts.append(_render_exposure_table(result))
    parts.append(_render_findings(findings))
    parts.append(
        "<footer>Generated by Portcullis - 100% local, no data left your machine.</footer>"
    )
    parts.append("</main></body></html>")
    return "\n".join(parts) + "\n"


def _render_header(result: ScanResult) -> str:
    grade_color = GRADE_COLORS.get(result.grade, "#555")
    counts = _severity_counts(result.findings)
    chips = "".join(
        f'<span class="pill" style="background:{SEVERITY_COLORS[sev]}">'
        f"{escape(str(sev))}: {counts[sev]}</span> "
        for sev in sorted(Severity, reverse=True)
        if counts[sev]
    )
    return (
        "<h1>Portcullis security report</h1>"
        f'<p class="sub">Scanned path: <code>{escape(str(result.stack.root))}</code></p>'
        '<p class="summary-line">'
        f'<span class="grade" style="background:{grade_color}">{escape(result.grade)}</span> '
        f"&nbsp;score {result.score}/100 &middot; {len(result.stack.services)} services "
        f"&middot; {len(result.findings)} findings</p>"
        f'<p class="meta">{chips or "no findings"}</p>'
    )


def _render_exposure_table(result: ScanResult) -> str:
    rows: list[str] = []
    for name in sorted(result.stack.services):
        service = result.stack.services[name]
        image = service.image.raw if service.image else ("(build)" if service.build else "?")
        exposure = result.exposures.get(name, Exposure.UNKNOWN)
        color = EXPOSURE_COLORS[exposure]
        rows.append(
            "<tr>"
            f"<td><code>{escape(name)}</code></td>"
            f"<td><code>{escape(image)}</code></td>"
            f'<td><span class="pill" style="background:{color}">{escape(str(exposure))}</span></td>'
            "</tr>"
        )
    return (
        "<h2>Service exposure</h2>"
        "<table><thead><tr><th>Service</th><th>Image</th><th>Exposure</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _render_findings(findings: list[Finding]) -> str:
    if not findings:
        return (
            '<h2>Findings</h2><p class="none">'
            "No findings at or above the requested severity.</p>"
        )
    blocks = [_render_finding(f) for f in findings]
    return "<h2>Findings</h2>" + "".join(blocks)


def _render_finding(finding: Finding) -> str:
    color = SEVERITY_COLORS[finding.severity]
    meta_bits = [f"<code>{escape(finding.rule_id)}</code>"]
    if finding.service:
        meta_bits.append(f"service <code>{escape(finding.service)}</code>")
    if finding.exposure is not None:
        meta_bits.append(f"exposure <strong>{escape(str(finding.exposure))}</strong>")
    if finding.source and finding.source != "portcullis":
        meta_bits.append(f"source <code>{escape(finding.source)}</code>")
    refs = ""
    if finding.references:
        links = " &middot; ".join(
            f'<a href="{escape(ref)}" rel="noreferrer noopener">{escape(ref)}</a>'
            for ref in finding.references
        )
        refs = f'<p class="refs">References: {links}</p>'
    return (
        f'<details style="border-left-color:{color}">'
        "<summary>"
        f'<span class="badge" style="background:{color}">{escape(str(finding.severity))}</span>'
        f'<span class="title">{escape(finding.title)}</span>'
        "</summary>"
        '<div class="body">'
        f'<p class="meta">{" &middot; ".join(meta_bits)}</p>'
        f"<p>{escape(finding.description)}</p>"
        f'<p><span class="label">Why it matters:</span> {escape(finding.risk)}</p>'
        f'<p class="fix"><span class="label">Fix:</span> {escape(finding.remediation)}</p>'
        f"{refs}"
        "</div></details>"
    )


def _severity_counts(findings: list[Finding]) -> dict[Severity, int]:
    counts = dict.fromkeys(Severity, 0)
    for finding in findings:
        counts[finding.severity] += 1
    return counts
