"""Interactive, self-contained HTML report.

On top of the static HTML report, this one adds three things the issue asks
for, all with **inline** CSS/JS/SVG and **zero external requests** (same
100%-local guarantee):

* filterable, searchable findings (by severity, service, rule, and free text),
  implemented in dependency-free vanilla JS over server-rendered cards;
* an exposure graph: services laid out in columns by exposure level, with the
  reverse-proxy services marked and edges drawn to what they route;
* a score sparkline from the local run history (see :mod:`portcullis.history`).

Every dynamic value is HTML-escaped, and the finding data the filters act on
is server-rendered into ``data-*`` attributes, so the report is fully readable
even with JavaScript disabled.
"""

from __future__ import annotations

from html import escape

from portcullis.history import Run
from portcullis.model import Exposure, Finding, ScanResult, Severity
from portcullis.report.html import EXPOSURE_COLORS, GRADE_COLORS, SEVERITY_COLORS

_EXPOSURE_ORDER = [Exposure.INTERNAL, Exposure.HOST, Exposure.LAN, Exposure.INTERNET]
_MAX_GRAPH_NODES = 80


def render_interactive(
    result: ScanResult, *, min_severity: Severity = Severity.INFO,
    history: list[Run] | None = None,
) -> str:
    findings = [f for f in result.findings if f.severity >= min_severity]
    parts = [
        "<!DOCTYPE html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>Portcullis interactive report</title>",
        f"<style>{_STYLE}</style></head><body><main>",
        _header(result, history or []),
        _graph(result),
        _filters(result, findings),
        _findings(findings),
        "<footer>Generated by Portcullis - 100% local, no data left your machine.</footer>",
        f"<script>{_SCRIPT}</script>",
        "</main></body></html>",
    ]
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Header + sparkline


def _header(result: ScanResult, history: list[Run]) -> str:
    grade_color = GRADE_COLORS.get(result.grade, "#555")
    spark = _sparkline(history)
    return (
        "<h1>Portcullis interactive report</h1>"
        f'<p class="sub">Scanned path: <code>{escape(str(result.stack.root))}</code></p>'
        '<div class="summary">'
        f'<span class="grade" style="background:{grade_color}">{escape(result.grade)}</span>'
        f'<span class="score">score {result.score}/100 &middot; '
        f"{len(result.stack.services)} services &middot; {len(result.findings)} findings</span>"
        f"{spark}</div>"
    )


def _sparkline(history: list[Run]) -> str:
    if len(history) < 2:
        return ""
    scores = [r.score for r in history][-40:]
    w, h = 160, 36
    n = len(scores)
    step = w / (n - 1)
    points = " ".join(
        f"{i * step:.1f},{h - (s / 100) * h:.1f}" for i, s in enumerate(scores)
    )
    last = scores[-1]
    dot_x = (n - 1) * step
    dot_y = h - (last / 100) * h
    return (
        '<span class="spark" title="score history">'
        f'<svg viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
        'preserveAspectRatio="none" role="img" aria-label="score history">'
        f'<polyline points="{points}" fill="none" stroke="#4a90d9" stroke-width="2"/>'
        f'<circle cx="{dot_x:.1f}" cy="{dot_y:.1f}" r="3" fill="#4a90d9"/>'
        f"</svg><small>{n} runs</small></span>"
    )


# ---------------------------------------------------------------------------
# Exposure graph (server-rendered SVG)


def _graph(result: ScanResult) -> str:
    names = sorted(result.stack.services)[:_MAX_GRAPH_NODES]
    truncated = len(result.stack.services) - len(names)
    columns: dict[Exposure, list[str]] = {e: [] for e in _EXPOSURE_ORDER}
    for name in names:
        exposure = result.exposures.get(name, Exposure.INTERNAL)
        columns.setdefault(exposure if exposure in columns else Exposure.INTERNAL, []).append(name)

    node_w, node_h, gap_y, gap_x = 150, 26, 12, 70
    top = 44
    col_x = {e: 20 + i * (node_w + gap_x) for i, e in enumerate(_EXPOSURE_ORDER)}
    centers: dict[str, tuple[float, float]] = {}
    node_svg: list[str] = []
    header_svg: list[str] = []

    for exposure in _EXPOSURE_ORDER:
        x = col_x[exposure]
        color = EXPOSURE_COLORS[exposure]
        header_svg.append(
            f'<text x="{x + node_w / 2:.0f}" y="26" text-anchor="middle" '
            f'class="colhead" fill="{color}">{escape(str(exposure))}</text>'
        )
        for row, name in enumerate(columns[exposure]):
            y = top + row * (node_h + gap_y)
            centers[name] = (x + node_w / 2, y + node_h / 2)
            is_proxy = name in result.routing.proxy_services
            stroke = "#1a1a1a" if is_proxy else color
            width = "2.5" if is_proxy else "1"
            label = escape(name if len(name) <= 20 else name[:18] + "…")
            tag = ('<title>reverse proxy</title>' if is_proxy else "")
            node_svg.append(
                f'<g>{tag}<rect x="{x}" y="{y}" width="{node_w}" height="{node_h}" rx="5" '
                f'fill="{color}" fill-opacity="0.18" stroke="{stroke}" stroke-width="{width}"/>'
                f'<text x="{x + 8}" y="{y + 17}" class="node">{label}'
                f'{" &#9733;" if is_proxy else ""}</text></g>'
            )

    edges_svg: list[str] = []
    routed = result.routing.internet_routed | result.routing.host_routed
    for proxy in result.routing.proxy_services:
        if proxy not in centers:
            continue
        px, py = centers[proxy]
        for target in routed:
            if target == proxy or target not in centers:
                continue
            tx, ty = centers[target]
            edges_svg.append(
                f'<line x1="{px:.0f}" y1="{py:.0f}" x2="{tx:.0f}" y2="{ty:.0f}" '
                'stroke="#888" stroke-width="1" stroke-opacity="0.4"/>'
            )

    rows = max((len(v) for v in columns.values()), default=0)
    height = top + max(rows, 1) * (node_h + gap_y)
    width = 20 + len(_EXPOSURE_ORDER) * (node_w + gap_x)
    note = (f'<p class="note">{truncated} more service(s) not shown.</p>' if truncated else "")
    return (
        "<h2>Exposure graph</h2>"
        '<div class="graph-wrap">'
        f'<svg viewBox="0 0 {width} {height:.0f}" width="{width}" height="{height:.0f}" '
        'role="img" aria-label="exposure graph">'
        f'{"".join(edges_svg)}{"".join(header_svg)}{"".join(node_svg)}</svg></div>'
        f"{note}"
        '<p class="legend">Columns are exposure levels (least to most exposed). '
        'A bold outline with &#9733; marks a reverse proxy; grey lines show what it routes.</p>'
    )


# ---------------------------------------------------------------------------
# Filters + findings


def _filters(result: ScanResult, findings: list[Finding]) -> str:
    services = sorted({f.service for f in findings if f.service})
    rules = sorted({f.rule_id for f in findings})
    sev_boxes = "".join(
        f'<label class="chk"><input type="checkbox" class="sev" value="{sev}" checked> '
        f'<span class="pill" style="background:{SEVERITY_COLORS[sev]}">{escape(str(sev))}</span>'
        "</label>"
        for sev in sorted(Severity, reverse=True)
    )
    service_opts = "".join(f'<option value="{escape(s)}">{escape(s)}</option>' for s in services)
    rule_opts = "".join(f'<option value="{escape(r)}">{escape(r)}</option>' for r in rules)
    return (
        "<h2>Findings</h2>"
        '<div class="filters">'
        f'<div class="sevs">{sev_boxes}</div>'
        f'<select id="svc"><option value="">all services</option>{service_opts}</select>'
        f'<select id="rule"><option value="">all rules</option>{rule_opts}</select>'
        '<input id="search" type="search" placeholder="search findings...">'
        '<span id="count" class="count"></span>'
        "</div>"
    )


def _findings(findings: list[Finding]) -> str:
    if not findings:
        return '<p class="none">No findings at or above the requested severity.</p>'
    return '<div id="findings">' + "".join(_card(f) for f in findings) + "</div>"


def _card(finding: Finding) -> str:
    color = SEVERITY_COLORS[finding.severity]
    searchable = escape(" ".join(filter(None, [
        finding.rule_id, finding.title, finding.service or "", finding.description,
        finding.risk, finding.remediation,
    ])).lower())
    refs = ""
    if finding.references:
        links = " &middot; ".join(
            f'<a href="{escape(r)}" rel="noreferrer noopener">{escape(r)}</a>'
            for r in finding.references
        )
        refs = f'<p class="refs">References: {links}</p>'
    meta = [f"<code>{escape(finding.rule_id)}</code>"]
    if finding.service:
        meta.append(f"service <code>{escape(finding.service)}</code>")
    if finding.exposure is not None:
        meta.append(f"exposure <strong>{escape(str(finding.exposure))}</strong>")
    return (
        f'<details class="finding" open data-severity="{finding.severity}" '
        f'data-service="{escape(finding.service or "")}" data-rule="{escape(finding.rule_id)}" '
        f'data-text="{searchable}" style="border-left-color:{color}">'
        "<summary>"
        f'<span class="badge" style="background:{color}">{escape(str(finding.severity))}</span>'
        f'<span class="title">{escape(finding.title)}</span></summary>'
        '<div class="body">'
        f'<p class="meta">{" &middot; ".join(meta)}</p>'
        f"<p>{escape(finding.description)}</p>"
        f'<p><span class="label">Why it matters:</span> {escape(finding.risk)}</p>'
        f'<p class="fix"><span class="label">Fix:</span> {escape(finding.remediation)}</p>'
        f"{refs}</div></details>"
    )


_STYLE = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial,
  sans-serif; line-height: 1.5; margin: 0; padding: 2rem 1rem; color: #1a1a1a;
  background: #f5f6f8; }
main { max-width: 68rem; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.2rem; margin: 2rem 0 .75rem; border-bottom: 1px solid #dcdfe4;
  padding-bottom: .3rem; }
.sub { color: #555; margin: 0 0 1rem; }
.summary { display: flex; align-items: center; gap: .8rem; flex-wrap: wrap; }
.grade { min-width: 2.4rem; text-align: center; color: #fff; font-weight: 700; font-size: 1.1rem;
  padding: .15rem .6rem; border-radius: .4rem; }
.spark { display: inline-flex; align-items: center; gap: .3rem; margin-left: auto; color: #666;
  font-size: .8rem; }
.graph-wrap { overflow-x: auto; background: #fff; border: 1px solid #e2e5ea; border-radius: .5rem;
  padding: .5rem; }
.colhead { font-size: 13px; font-weight: 700; text-transform: uppercase; }
.node { font-size: 12px; fill: #1a1a1a; font-family: ui-monospace, Menlo, Consolas, monospace; }
.legend, .note { color: #666; font-size: .82rem; }
.filters { display: flex; gap: .6rem; align-items: center; flex-wrap: wrap; margin-bottom: 1rem; }
.sevs { display: flex; gap: .4rem; flex-wrap: wrap; }
.chk { display: inline-flex; align-items: center; gap: .2rem; font-size: .8rem; cursor: pointer; }
.pill, .badge { display: inline-block; color: #fff; font-size: .72rem; font-weight: 700;
  padding: .05rem .4rem; border-radius: .3rem; text-transform: uppercase; }
select, #search { padding: .3rem .5rem; border: 1px solid #ccd2da; border-radius: .35rem;
  background: #fff; font-size: .85rem; }
#search { flex: 1; min-width: 8rem; }
.count { color: #666; font-size: .8rem; }
details.finding { background: #fff; border: 1px solid #e2e5ea; border-left-width: 4px;
  border-radius: .4rem; margin: .5rem 0; }
summary { cursor: pointer; padding: .6rem .9rem; font-weight: 600; display: flex; gap: .6rem;
  align-items: center; list-style: none; }
summary::-webkit-details-marker { display: none; }
summary .title { flex: 1; }
.body { padding: 0 .9rem .8rem; }
.meta { color: #666; font-size: .82rem; }
.label { font-weight: 700; } .fix .label { color: #2e7d32; }
.refs { font-size: .82rem; word-break: break-all; }
code { font-family: ui-monospace, Menlo, Consolas, monospace; font-size: .88em; background: #eceef1;
  padding: .05rem .3rem; border-radius: .25rem; }
.none { color: #2e7d32; font-weight: 600; }
footer { margin-top: 2.5rem; color: #888; font-size: .8rem; text-align: center; }
@media (prefers-color-scheme: dark) {
  body { background: #16181d; color: #e6e8ec; }
  h2 { border-color: #2c3038; } .sub, .meta, .legend, .note, .count, footer { color: #9aa0a8; }
  .graph-wrap, select, #search, details.finding { background: #1e2127; border-color: #2c3038; }
  code { background: #2c3038; } .node { fill: #e6e8ec; }
}
"""

_SCRIPT = """
(function () {
  var search = document.getElementById('search');
  var svc = document.getElementById('svc');
  var rule = document.getElementById('rule');
  var count = document.getElementById('count');
  var sevs = Array.prototype.slice.call(document.querySelectorAll('.sev'));
  var cards = Array.prototype.slice.call(document.querySelectorAll('.finding'));
  function apply() {
    var q = (search.value || '').toLowerCase();
    var checked = {};
    sevs.forEach(function (c) { checked[c.value] = c.checked; });
    var shown = 0;
    cards.forEach(function (card) {
      var ok = checked[card.getAttribute('data-severity')] !== false;
      if (ok && svc.value) ok = card.getAttribute('data-service') === svc.value;
      if (ok && rule.value) ok = card.getAttribute('data-rule') === rule.value;
      if (ok && q) ok = card.getAttribute('data-text').indexOf(q) !== -1;
      card.style.display = ok ? '' : 'none';
      if (ok) shown++;
    });
    if (count) count.textContent = 'showing ' + shown + ' of ' + cards.length;
  }
  [search, svc, rule].forEach(function (el) { if (el) { el.addEventListener('input', apply); } });
  sevs.forEach(function (c) { c.addEventListener('change', apply); });
  apply();
})();
"""
